import { styleTags, tags as t } from '@lezer/highlight';

export const feelHighlighting = styleTags({
  'StringLiteral': t.string,
  'NumericLiteral': t.number,
  'BooleanLiteral': t.bool,
  'AtLiteral!': t.special(t.string),
  'CompareOp': t.compareOperator,
  'ArithOp': t.arithmeticOperator,
  'for if then else some every satisfies between': t.controlKeyword,
  'in return instance of and or': t.operatorKeyword,
  'function': t.definitionKeyword,
  'Type/...': t.typeName,
  'as': t.keyword,
  'Wildcard': t.special,
  'null': t.null,
  '","': t.separator,
  '"[" "]"': t.squareBracket,
  '"{" "}"': t.brace,
  '"(" ")"': t.paren,
  'LineComment': t.lineComment,
  'BlockComment': t.blockComment,
  'VariableName! "?"': t.local(t.variableName),
  'DateTimeConstructor! SpecialFunctionName!': t.special(t.variableName),
  'List Interval': t.list,
  'Context': t.definition(t.literal),
  'Name!': t.definition(t.variableName),
  'Key/Name! PathExpression/VariableName!': t.definition(t.propertyName),
  '".." "."': t.punctuation
});